project:
  type: book
  output-dir: _site

book:
  title: "recetario"
  author: "Antonio Ortiz-Ambriz"
  date: last-modified
  sidebar:
    search: true
  chapters:
    - index.qmd
    - part: "Panes"
      chapters:
      - panes/shokupan.qmd
      - panes/focaccia.qmd
    - part: "Postres"
      chapters:
      - postres/pastel_de_aceite.qmd

format:
  html:
    theme: cosmo
    toc: true
  pdf:
    documentclass: report
    papersize: a5paper
    toc: true
