---
title: "Focaccia"
categories: "Panes"
---
## Ingredientes

* (75%) 450 g de agua
* (2%) 12g de levadura seca activa
* (2%) 12 g de azúcar
* (100%) 600 g de harina de trigo
* (2%) 12 g de sal
* (20%) 120 g de aceite de oliva, dividido en dos partes

## Instrucciones

Mezcla el agua con la levadura y el azucar. Deja reposar por 10 minutos hasta que la levadura se active y se vea espumosa.

En otro tazón, mezcla la harina y la sal. Vie

Haz un volcán con la harina, vierte la mitad del aceite en la parte de afuera y agrega la mezcla de agua y levadura en la parte de adentro. Mezcla de adentro hacia afuera hasta que se integre toda la harina. 

Vierte en un tazón grande y cubre, con tapa o con plástico autoadherente, y deja reposar hasta que la masa doble su tamaño, más o menos una hora.

Pasa la masa a una bandeja para hornear engrasada con aceite de oliva y estira con las manos hasta que cubra toda la bandeja. Cubre y deja reposar por 30 minutos. 

Vierte el resto del aceite de oliva sobre la masaa y haz hoyos con los dedos. Agrega hierbas al gusto. 

Hornea a 220°C por 20-25 minutos, hasta que esté dorada.
