---
title: "Shokupan"
categories: "Panes"
---
::: {.callout-note icon=false}

Receta adaptada de [Just One Cookbook](https://www.justonecookbook.com/shokupan-japanese-milk-bread/).

:::

## Ingredientes

* (65% - 70% dependiendo de la humedad) 276g - 300g de leche
* (2%) 9 g de levadura seca activa
* (8.5%) 36 g de azúcar
* (100%) 425 g de harina de trigo
* (2%) 9 g de sal
* (7%) 30 g de mantequilla sin sal, fria.

## Instrucciones

Mezcla la leche, el azucar y la levadura en una taza y deja reposar por 10 minutos. Si el ambiente está caliente, usa sólo 100 g de leche, y el resto mantenlo en el refrigerador hasta que sea hora de integrarlo con la harina. 
Mezcla en el tazón de la batidora la harina y la sal. Haz un hoyo en el centro y agrega la mezcla de leche, azucar y levadura. 

### Amasado

#### Batidora 

* Velocidad 2 por 2 o 3 minutos, hasta que se integre
* Velocidad 4 por 4 minutos hasta que se vea suave.
* Velocidad 6 por 3 minutos hasta que la masa se despegue de las paredes del tazón. 
* Agregar la mantequilla
* Velocidad 6 por 2 o 3 minutos hasta que esté elástica y se despegue de las paredes del tazón. 
* Velocidad 4 por 1 o 2 minutos para relajar la masa. 

#### A mano
* Usa un raspador de masa para integrar la masa en una bola suave
* Levanta la masa y golpeala contra la mesa. Vuelve a enrollarla desde la parte de abajo, y has una bola con la parte suave hacia arriba. Repite este proceso 5 voeces en total. 
* Vuelve a usar el raspador para haer una bola suave y pasa a un bol para fermentar. 

### Formado 
* Saca la masa del tazón y presiona con los dedos para desinflarla. 
* Divide la masa en cuatro partes iguales y forma bolas. Mantén en todo momento la parte suave hacia arriba.
* Cubre con un paño húmedo y deja reposar 10 minutos.
* Aplana la bola con la mano, o con un rodillo hasta formar un rectángulo. 
* Dobla el rectángulo en tres partes, y vuelve a aplanar. Enrolla la tira que queda para formar un cilindro corto. 
* Coloca los cilindros en un molde para pan con tapa, colocando la parte suave hacia arriba. 
* Coloca la tapa y deja fermentar hasta que la masa llegue a 2 cm del borde del molde.

### Horneado
* Precalienta el horno a 210°C. 
* Hornea por 30 minutos. 

