---
title: "Pastel de Aceite de Oliva"
categories: "Panes"
---
::: {.callout-note icon=false}

Receta adaptada de [Food52](https://food52.com/recipes/26709-maialino-s-olive-oil-cake.)

:::

## Ingredientes

* 250g de Harina de trigo
* 9g de sal
* 5g de bicarbonato de sodio
* 5g de polvo para hornear
* 185g de huevos (aproximadamente 3 huevos grandes)
* 250g de azúcar
* 220g de aceite de oliva extra virgen
* 265g de leche
* 65g de brandy
* La ralladura y el jugo de una naranja.

## Instrucciones

* Precalienta el horno a 175°C. Engrasa un molde, coloca una cucharada de harina, sacude, y desarta el exceso. 

* Mezcla en un tazón la harina, la sal, el bicarbonato y el polvo para hornear.

* En otro tazón (o preferiblemente en la batidora) bate los huevos y el azucar hasta que queden cremosos y agrega el aceite poco a poco. 

* En un tercer recipiente mezcla la leche, el brandy, la ralladura y el jugo de naranja.

* Integra poco a poco la mezcla de harina con la mezcla de huevos y aceite, alternando con la mezcla de leche y brandy, procurando que quede homogéneo en cada paso.

* Vierte en el molde, y hornea más o menos 50 minutos, hasta que la superficie este dorada y fime al tacto. Deja enfriar antes de desmoldar. 

Se puede decorar con crema batida y frutas frescas o con azucar glass espolvoreada. 
